services:
  ssodb:
    image: postgres:17
    container_name: sso_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - sso_pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ssonetwork

  ssoapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sso_app
    restart: on-failure
    depends_on:
      ssodb:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8081:${REST_PORT}"
      - "50051:${GRPC_PORT}"
    networks:
      - iappnetwork
      - ssonetwork

networks:
  iappnetwork:
    external: true
  ssonetwork:
    driver: bridge

volumes:
  sso_pgdata: